### ISSUE TITLE
Retrofit2 OnResponse Method

### ISSUE THREAD

**Issue by Alpkant** [JamperCin/searchingspinner#1]
I am using Retrofit2 to get list of data when i try to all addEntries() method in the onResponse method of the Retrofit (Which uses UI Thread ) gives android.view.ViewRootImpl$CalledFromWrongThreadException i tried everything to make operation in UI thread (Handlers,runOnUIThread,Loopers) but it still gives error. If you want to see log here it is. 

W/System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
W/System.err:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6855)
W/System.err:     at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1075)
W/System.err:     at android.view.ViewGroup.invalidateChild(ViewGroup.java:5242)
W/System.err:     at android.view.View.invalidateInternal(View.java:13574)
W/System.err:     at android.view.View.invalidate(View.java:13510)
W/System.err:     at android.widget.TextView.invalidateRegion(TextView.java:5346)
W/System.err:     at android.widget.TextView.invalidateCursor(TextView.java:5289)
W/System.err:     at android.widget.TextView.spanChange(TextView.java:8283)
W/System.err:     at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:10397)
W/System.err:     at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:1228)
W/System.err:     at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:767)
W/System.err:     at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
W/System.err:     at android.text.Selection.setSelection(Selection.java:76)
W/System.err:     at android.text.Selection.setSelection(Selection.java:87)
W/System.err:     at android.text.method.ArrowKeyMovementMethod.initialize(ArrowKeyMovementMethod.java:312)
W/System.err:     at android.widget.TextView.setText(TextView.java:4467)
W/System.err:     at android.widget.TextView.setText(TextView.java:4336)
W/System.err:     at android.widget.EditText.setText(EditText.java:89)
W/System.err:     at android.widget.TextView.setText(TextView.java:4311)
W/System.err:     at com.jamper.searchspinner.SearchingSpinner.setDefaultItem(SearchingSpinner.java:168)
W/System.err:     at com.jamper.searchspinner.SearchingSpinner.access$300(SearchingSpinner.java:17)
W/System.err:     at com.jamper.searchspinner.SearchingSpinner$3.run(SearchingSpinner.java:146)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by JamperCin** [comment]
Can you post the portion of that code?
MoreOver, addEntries() method already runs in the background so no need to call it from AsynTask
and it accepts an ArrayList<String> as a parameter

Add your data from the response to an ArrayList and pass that whole array to the *addEntries()* method
